/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Timestamp = IDL.Nat;
export const Category = IDL.Variant({
  'scholarship' : IDL.Null,
  'internship' : IDL.Null,
  'creative' : IDL.Null,
  'arts' : IDL.Null,
  'conference' : IDL.Null,
  'community' : IDL.Null,
  'culture' : IDL.Null,
  'athletics' : IDL.Null,
  'academic' : IDL.Null,
  'debate' : IDL.Null,
  'design' : IDL.Null,
  'leadership' : IDL.Null,
  'competition' : IDL.Null,
  'business' : IDL.Null,
  'environment' : IDL.Null,
  'entrepreneurship' : IDL.Null,
  'coding' : IDL.Null,
  'volunteering' : IDL.Null,
  'health' : IDL.Null,
});
export const EventInput = IDL.Record({
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'cost' : IDL.Text,
  'date' : Timestamp,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'category' : Category,
  'location' : IDL.Text,
});
export const OpportunityId = IDL.Nat;
export const Status = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
  'closingSoon' : IDL.Null,
});
export const Marker = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
export const FactorRatings = IDL.Record({
  'recognition' : IDL.Float64,
  'difficulty' : IDL.Float64,
  'skillDevelopment' : IDL.Float64,
  'networking' : IDL.Float64,
  'timeCommitment' : IDL.Float64,
  'leadership' : IDL.Float64,
  'relevance' : IDL.Float64,
  'worthYourTime' : IDL.Float64,
  'priceValue' : IDL.Float64,
  'uniApplicationValue' : IDL.Float64,
});
export const Opportunity = IDL.Record({
  'id' : OpportunityId,
  'status' : Status,
  'organizer' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'applyUrl' : IDL.Opt(IDL.Text),
  'venue' : IDL.Text,
  'isPrototype' : IDL.Bool,
  'ageRange' : IDL.Text,
  'cost' : IDL.Text,
  'date' : Timestamp,
  'description' : IDL.Text,
  'deadline' : Timestamp,
  'category' : Category,
  'marker' : Marker,
  'factorRatings' : FactorRatings,
  'registrationUrl' : IDL.Opt(IDL.Text),
  'location' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const CostFilter = IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null });
export const OpportunityFilter = IDL.Record({
  'status' : IDL.Opt(Status),
  'cost' : IDL.Opt(CostFilter),
  'category' : IDL.Opt(Category),
});
export const UserId = IDL.Principal;
export const Organizer = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const FactorScore = IDL.Record({
  'weight' : IDL.Float64,
  'name' : IDL.Text,
  'rating' : IDL.Float64,
});
export const RatingExplanation = IDL.Record({
  'factors' : IDL.Vec(FactorScore),
  'overall' : IDL.Float64,
});
export const RecommendationMode = IDL.Variant({
  'bestValue' : IDL.Null,
  'university' : IDL.Null,
  'closingSoon' : IDL.Null,
  'highestRated' : IDL.Null,
  'skills' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEvent' : IDL.Func([EventInput], [Opportunity], []),
  'deleteAccount' : IDL.Func([IDL.Text], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'filterByInterests' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'filterOpportunities' : IDL.Func(
      [OpportunityFilter],
      [IDL.Vec(Opportunity)],
      ['query'],
    ),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCatalog' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getInterests' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getOpportunity' : IDL.Func(
      [OpportunityId],
      [IDL.Opt(Opportunity)],
      ['query'],
    ),
  'getOrganizerProfile' : IDL.Func([], [IDL.Opt(Organizer)], ['query']),
  'getRatingExplanation' : IDL.Func(
      [OpportunityId],
      [IDL.Opt(RatingExplanation)],
      ['query'],
    ),
  'getSavedOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isOrganizer' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyEvents' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'recommend' : IDL.Func(
      [RecommendationMode],
      [IDL.Vec(Opportunity)],
      ['query'],
    ),
  'recommendByInterests' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
  'saveOpportunity' : IDL.Func([OpportunityId], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchOpportunities' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Opportunity)],
      ['query'],
    ),
  'setInterests' : IDL.Func([IDL.Vec(Category)], [], []),
  'signUpAsOrganizer' : IDL.Func([IDL.Text], [Organizer], []),
  'unsaveOpportunity' : IDL.Func([OpportunityId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Timestamp = IDL.Nat;
  const Category = IDL.Variant({
    'scholarship' : IDL.Null,
    'internship' : IDL.Null,
    'creative' : IDL.Null,
    'arts' : IDL.Null,
    'conference' : IDL.Null,
    'community' : IDL.Null,
    'culture' : IDL.Null,
    'athletics' : IDL.Null,
    'academic' : IDL.Null,
    'debate' : IDL.Null,
    'design' : IDL.Null,
    'leadership' : IDL.Null,
    'competition' : IDL.Null,
    'business' : IDL.Null,
    'environment' : IDL.Null,
    'entrepreneurship' : IDL.Null,
    'coding' : IDL.Null,
    'volunteering' : IDL.Null,
    'health' : IDL.Null,
  });
  const EventInput = IDL.Record({
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'cost' : IDL.Text,
    'date' : Timestamp,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'category' : Category,
    'location' : IDL.Text,
  });
  const OpportunityId = IDL.Nat;
  const Status = IDL.Variant({
    'closed' : IDL.Null,
    'open' : IDL.Null,
    'closingSoon' : IDL.Null,
  });
  const Marker = IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 });
  const FactorRatings = IDL.Record({
    'recognition' : IDL.Float64,
    'difficulty' : IDL.Float64,
    'skillDevelopment' : IDL.Float64,
    'networking' : IDL.Float64,
    'timeCommitment' : IDL.Float64,
    'leadership' : IDL.Float64,
    'relevance' : IDL.Float64,
    'worthYourTime' : IDL.Float64,
    'priceValue' : IDL.Float64,
    'uniApplicationValue' : IDL.Float64,
  });
  const Opportunity = IDL.Record({
    'id' : OpportunityId,
    'status' : Status,
    'organizer' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'applyUrl' : IDL.Opt(IDL.Text),
    'venue' : IDL.Text,
    'isPrototype' : IDL.Bool,
    'ageRange' : IDL.Text,
    'cost' : IDL.Text,
    'date' : Timestamp,
    'description' : IDL.Text,
    'deadline' : Timestamp,
    'category' : Category,
    'marker' : Marker,
    'factorRatings' : FactorRatings,
    'registrationUrl' : IDL.Opt(IDL.Text),
    'location' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const CostFilter = IDL.Variant({ 'free' : IDL.Null, 'paid' : IDL.Null });
  const OpportunityFilter = IDL.Record({
    'status' : IDL.Opt(Status),
    'cost' : IDL.Opt(CostFilter),
    'category' : IDL.Opt(Category),
  });
  const UserId = IDL.Principal;
  const Organizer = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const FactorScore = IDL.Record({
    'weight' : IDL.Float64,
    'name' : IDL.Text,
    'rating' : IDL.Float64,
  });
  const RatingExplanation = IDL.Record({
    'factors' : IDL.Vec(FactorScore),
    'overall' : IDL.Float64,
  });
  const RecommendationMode = IDL.Variant({
    'bestValue' : IDL.Null,
    'university' : IDL.Null,
    'closingSoon' : IDL.Null,
    'highestRated' : IDL.Null,
    'skills' : IDL.Null,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEvent' : IDL.Func([EventInput], [Opportunity], []),
    'deleteAccount' : IDL.Func([IDL.Text], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'filterByInterests' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'filterOpportunities' : IDL.Func(
        [OpportunityFilter],
        [IDL.Vec(Opportunity)],
        ['query'],
      ),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCatalog' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getInterests' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getOpportunity' : IDL.Func(
        [OpportunityId],
        [IDL.Opt(Opportunity)],
        ['query'],
      ),
    'getOrganizerProfile' : IDL.Func([], [IDL.Opt(Organizer)], ['query']),
    'getRatingExplanation' : IDL.Func(
        [OpportunityId],
        [IDL.Opt(RatingExplanation)],
        ['query'],
      ),
    'getSavedOpportunities' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isOrganizer' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyEvents' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'recommend' : IDL.Func(
        [RecommendationMode],
        [IDL.Vec(Opportunity)],
        ['query'],
      ),
    'recommendByInterests' : IDL.Func([], [IDL.Vec(Opportunity)], ['query']),
    'saveOpportunity' : IDL.Func([OpportunityId], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchOpportunities' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Opportunity)],
        ['query'],
      ),
    'setInterests' : IDL.Func([IDL.Vec(Category)], [], []),
    'signUpAsOrganizer' : IDL.Func([IDL.Text], [Organizer], []),
    'unsaveOpportunity' : IDL.Func([OpportunityId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };