/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.2.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Cell {
    value: Value;
    name: string;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface EventInput {
    title: string;
    venue: string;
    cost: string;
    date: Timestamp;
    description: string;
    deadline: Timestamp;
    category: Category;
    location: string;
}
export interface FactorRatings {
    recognition: number;
    difficulty: number;
    skillDevelopment: number;
    networking: number;
    timeCommitment: number;
    leadership: number;
    relevance: number;
    worthYourTime: number;
    priceValue: number;
    uniApplicationValue: number;
}
export interface FactorScore {
    weight: number;
    name: string;
    rating: number;
}
export interface Marker {
    x: number;
    y: number;
}
export interface Opportunity {
    id: OpportunityId;
    status: Status;
    organizer: string;
    title: string;
    duration: string;
    applyUrl?: string;
    venue: string;
    isPrototype: boolean;
    ageRange: string;
    cost: string;
    date: Timestamp;
    description: string;
    deadline: Timestamp;
    category: Category;
    marker: Marker;
    factorRatings: FactorRatings;
    registrationUrl?: string;
    location: string;
}
export interface OpportunityFilter {
    status?: Status;
    cost?: CostFilter;
    category?: Category;
}
export type OpportunityId = bigint;
export interface Organizer {
    id: UserId;
    name: string;
    createdAt: Timestamp;
}
export interface RatingExplanation {
    factors: Array<FactorScore>;
    overall: number;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Timestamp = bigint;
export type UserId = Principal;
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum Category {
    scholarship = "scholarship",
    internship = "internship",
    creative = "creative",
    arts = "arts",
    conference = "conference",
    community = "community",
    culture = "culture",
    athletics = "athletics",
    academic = "academic",
    debate = "debate",
    design = "design",
    leadership = "leadership",
    competition = "competition",
    business = "business",
    environment = "environment",
    entrepreneurship = "entrepreneurship",
    coding = "coding",
    volunteering = "volunteering",
    health = "health"
}
export enum CostFilter {
    free = "free",
    paid = "paid"
}
export enum RecommendationMode {
    bestValue = "bestValue",
    university = "university",
    closingSoon = "closingSoon",
    highestRated = "highestRated",
    skills = "skills"
}
export enum Status {
    closed = "closed",
    open = "open",
    closingSoon = "closingSoon"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create a new event. Requires a signed-in organizer.
     */
    createEvent(input: EventInput): Promise<Opportunity>;
    /**
     * / Delete the caller's account, wiping saved opportunities and interests.
     * / Requires a signed-in caller and the confirmation string "DELETE".
     */
    deleteAccount(confirmation: string): Promise<void>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Filter opportunities to those matching the caller's interests. Requires a signed-in caller.
     */
    filterByInterests(): Promise<Array<Opportunity>>;
    /**
     * / Filter opportunities by category, cost, and status. Public.
     */
    filterOpportunities(filter: OpportunityFilter): Promise<Array<Opportunity>>;
    getApiDoc(): Promise<string>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Return the full opportunity catalog. Public; no sign-in required.
     */
    getCatalog(): Promise<Array<Opportunity>>;
    /**
     * / Return the 19 opportunity categories. Public.
     */
    getCategories(): Promise<Array<Category>>;
    /**
     * / Return the caller's selected interest categories. Requires a signed-in caller.
     */
    getInterests(): Promise<Array<Category>>;
    /**
     * / Look up a single opportunity by id. Public.
     */
    getOpportunity(id: OpportunityId): Promise<Opportunity | null>;
    /**
     * / Return the caller's organizer profile, if any. Requires a signed-in caller.
     */
    getOrganizerProfile(): Promise<Organizer | null>;
    /**
     * / Return the per-factor rating breakdown for an opportunity. Public.
     */
    getRatingExplanation(id: OpportunityId): Promise<RatingExplanation | null>;
    /**
     * / Return the caller's saved opportunities. Requires a signed-in caller.
     */
    getSavedOpportunities(): Promise<Array<Opportunity>>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Whether the caller is a registered organizer. Requires a signed-in caller.
     */
    isOrganizer(): Promise<boolean>;
    /**
     * / Return the events created by the caller. Requires a signed-in organizer.
     */
    listMyEvents(): Promise<Array<Opportunity>>;
    /**
     * / Return opportunities ordered by the given recommendation mode. Public.
     */
    recommend(mode: RecommendationMode): Promise<Array<Opportunity>>;
    /**
     * / Re-rank/surface opportunities by the caller's interests. Requires a signed-in caller.
     */
    recommendByInterests(): Promise<Array<Opportunity>>;
    /**
     * / Save an opportunity to the caller's saved list. Requires a signed-in caller.
     */
    saveOpportunity(id: OpportunityId): Promise<void>;
    schema(): Promise<string>;
    /**
     * / Search opportunities by keyword across title, organizer, and description. Public.
     */
    searchOpportunities(keyword: string): Promise<Array<Opportunity>>;
    /**
     * / Set the caller's selected interest categories (multi-select, replaces). Requires a signed-in caller.
     */
    setInterests(selected: Array<Category>): Promise<void>;
    /**
     * / Sign up the caller as an organizer. Requires a signed-in caller.
     */
    signUpAsOrganizer(name: string): Promise<Organizer>;
    /**
     * / Remove an opportunity from the caller's saved list. Requires a signed-in caller.
     */
    unsaveOpportunity(id: OpportunityId): Promise<void>;
}
import type { Category as _Category, Cell as _Cell, CostFilter as _CostFilter, Error as _Error, EventInput as _EventInput, FactorRatings as _FactorRatings, Marker as _Marker, Opportunity as _Opportunity, OpportunityFilter as _OpportunityFilter, OpportunityId as _OpportunityId, Organizer as _Organizer, RatingExplanation as _RatingExplanation, RecommendationMode as _RecommendationMode, Result as _Result, Result__1 as _Result__1, Status as _Status, Timestamp as _Timestamp, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createEvent(arg0: EventInput): Promise<Opportunity> {
        if (this.processError) {
            try {
                const result = await this.actor.createEvent(to_candid_EventInput_n7(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Opportunity_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEvent(to_candid_EventInput_n7(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Opportunity_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteAccount(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAccount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAccount(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterByInterests(): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterByInterests();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterByInterests();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async filterOpportunities(arg0: OpportunityFilter): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterOpportunities(to_candid_OpportunityFilter_n27(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterOpportunities(to_candid_OpportunityFilter_n27(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCatalog(): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCatalog();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCatalog();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getInterests(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getInterests();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInterests();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpportunity(arg0: OpportunityId): Promise<Opportunity | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpportunity(arg0);
                return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpportunity(arg0);
            return from_candid_opt_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrganizerProfile(): Promise<Organizer | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrganizerProfile();
                return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrganizerProfile();
            return from_candid_opt_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRatingExplanation(arg0: OpportunityId): Promise<RatingExplanation | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getRatingExplanation(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRatingExplanation(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSavedOpportunities(): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSavedOpportunities();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSavedOpportunities();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isOrganizer(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isOrganizer();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isOrganizer();
            return result;
        }
    }
    async listMyEvents(): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyEvents();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyEvents();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async recommend(arg0: RecommendationMode): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.recommend(to_candid_RecommendationMode_n39(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recommend(to_candid_RecommendationMode_n39(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async recommendByInterests(): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.recommendByInterests();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recommendByInterests();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveOpportunity(arg0: OpportunityId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveOpportunity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveOpportunity(arg0);
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchOpportunities(arg0: string): Promise<Array<Opportunity>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchOpportunities(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchOpportunities(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async setInterests(arg0: Array<Category>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setInterests(to_candid_vec_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setInterests(to_candid_vec_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async signUpAsOrganizer(arg0: string): Promise<Organizer> {
        if (this.processError) {
            try {
                const result = await this.actor.signUpAsOrganizer(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.signUpAsOrganizer(arg0);
            return result;
        }
    }
    async unsaveOpportunity(arg0: OpportunityId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveOpportunity(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveOpportunity(arg0);
            return result;
        }
    }
}
function from_candid_Category_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Opportunity_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Opportunity): Opportunity {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Opportunity]): Opportunity | null {
    return value.length === 0 ? null : from_candid_Opportunity_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Organizer]): Organizer | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_RatingExplanation]): RatingExplanation | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OpportunityId;
    status: _Status;
    organizer: string;
    title: string;
    duration: string;
    applyUrl: [] | [string];
    venue: string;
    isPrototype: boolean;
    ageRange: string;
    cost: string;
    date: _Timestamp;
    description: string;
    deadline: _Timestamp;
    category: _Category;
    marker: _Marker;
    factorRatings: _FactorRatings;
    registrationUrl: [] | [string];
    location: string;
}): {
    id: OpportunityId;
    status: Status;
    organizer: string;
    title: string;
    duration: string;
    applyUrl?: string;
    venue: string;
    isPrototype: boolean;
    ageRange: string;
    cost: string;
    date: Timestamp;
    description: string;
    deadline: Timestamp;
    category: Category;
    marker: Marker;
    factorRatings: FactorRatings;
    registrationUrl?: string;
    location: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n13(_uploadFile, _downloadFile, value.status),
        organizer: value.organizer,
        title: value.title,
        duration: value.duration,
        applyUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.applyUrl)),
        venue: value.venue,
        isPrototype: value.isPrototype,
        ageRange: value.ageRange,
        cost: value.cost,
        date: value.date,
        description: value.description,
        deadline: value.deadline,
        category: from_candid_Category_n16(_uploadFile, _downloadFile, value.category),
        marker: value.marker,
        factorRatings: value.factorRatings,
        registrationUrl: record_opt_to_undefined(from_candid_opt_n15(_uploadFile, _downloadFile, value.registrationUrl)),
        location: value.location
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n20(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n24(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    open: null;
} | {
    closingSoon: null;
}): Status {
    return "closed" in value ? Status.closed : "open" in value ? Status.open : "closingSoon" in value ? Status.closingSoon : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scholarship: null;
} | {
    internship: null;
} | {
    creative: null;
} | {
    arts: null;
} | {
    conference: null;
} | {
    community: null;
} | {
    culture: null;
} | {
    athletics: null;
} | {
    academic: null;
} | {
    debate: null;
} | {
    design: null;
} | {
    leadership: null;
} | {
    competition: null;
} | {
    business: null;
} | {
    environment: null;
} | {
    entrepreneurship: null;
} | {
    coding: null;
} | {
    volunteering: null;
} | {
    health: null;
}): Category {
    return "scholarship" in value ? Category.scholarship : "internship" in value ? Category.internship : "creative" in value ? Category.creative : "arts" in value ? Category.arts : "conference" in value ? Category.conference : "community" in value ? Category.community : "culture" in value ? Category.culture : "athletics" in value ? Category.athletics : "academic" in value ? Category.academic : "debate" in value ? Category.debate : "design" in value ? Category.design : "leadership" in value ? Category.leadership : "competition" in value ? Category.competition : "business" in value ? Category.business : "environment" in value ? Category.environment : "entrepreneurship" in value ? Category.entrepreneurship : "coding" in value ? Category.coding : "volunteering" in value ? Category.volunteering : "health" in value ? Category.health : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Opportunity>): Array<Opportunity> {
    return value.map((x)=>from_candid_Opportunity_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Category>): Array<Category> {
    return value.map((x)=>from_candid_Category_n16(_uploadFile, _downloadFile, x));
}
function to_candid_Category_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_CostFilter_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CostFilter): _CostFilter {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_EventInput_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EventInput): _EventInput {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_OpportunityFilter_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OpportunityFilter): _OpportunityFilter {
    return to_candid_record_n28(_uploadFile, _downloadFile, value);
}
function to_candid_RecommendationMode_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationMode): _RecommendationMode {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: Status;
    cost?: CostFilter;
    category?: Category;
}): {
    status: [] | [_Status];
    cost: [] | [_CostFilter];
    category: [] | [_Category];
} {
    return {
        status: value.status ? candid_some(to_candid_Status_n29(_uploadFile, _downloadFile, value.status)) : candid_none(),
        cost: value.cost ? candid_some(to_candid_CostFilter_n31(_uploadFile, _downloadFile, value.cost)) : candid_none(),
        category: value.category ? candid_some(to_candid_Category_n9(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    venue: string;
    cost: string;
    date: Timestamp;
    description: string;
    deadline: Timestamp;
    category: Category;
    location: string;
}): {
    title: string;
    venue: string;
    cost: string;
    date: _Timestamp;
    description: string;
    deadline: _Timestamp;
    category: _Category;
    location: string;
} {
    return {
        title: value.title,
        venue: value.venue,
        cost: value.cost,
        date: value.date,
        description: value.description,
        deadline: value.deadline,
        category: to_candid_Category_n9(_uploadFile, _downloadFile, value.category),
        location: value.location
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    scholarship: null;
} | {
    internship: null;
} | {
    creative: null;
} | {
    arts: null;
} | {
    conference: null;
} | {
    community: null;
} | {
    culture: null;
} | {
    athletics: null;
} | {
    academic: null;
} | {
    debate: null;
} | {
    design: null;
} | {
    leadership: null;
} | {
    competition: null;
} | {
    business: null;
} | {
    environment: null;
} | {
    entrepreneurship: null;
} | {
    coding: null;
} | {
    volunteering: null;
} | {
    health: null;
} {
    return value == Category.scholarship ? {
        scholarship: null
    } : value == Category.internship ? {
        internship: null
    } : value == Category.creative ? {
        creative: null
    } : value == Category.arts ? {
        arts: null
    } : value == Category.conference ? {
        conference: null
    } : value == Category.community ? {
        community: null
    } : value == Category.culture ? {
        culture: null
    } : value == Category.athletics ? {
        athletics: null
    } : value == Category.academic ? {
        academic: null
    } : value == Category.debate ? {
        debate: null
    } : value == Category.design ? {
        design: null
    } : value == Category.leadership ? {
        leadership: null
    } : value == Category.competition ? {
        competition: null
    } : value == Category.business ? {
        business: null
    } : value == Category.environment ? {
        environment: null
    } : value == Category.entrepreneurship ? {
        entrepreneurship: null
    } : value == Category.coding ? {
        coding: null
    } : value == Category.volunteering ? {
        volunteering: null
    } : value == Category.health ? {
        health: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    closed: null;
} | {
    open: null;
} | {
    closingSoon: null;
} {
    return value == Status.closed ? {
        closed: null
    } : value == Status.open ? {
        open: null
    } : value == Status.closingSoon ? {
        closingSoon: null
    } : value;
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CostFilter): {
    free: null;
} | {
    paid: null;
} {
    return value == CostFilter.free ? {
        free: null
    } : value == CostFilter.paid ? {
        paid: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecommendationMode): {
    bestValue: null;
} | {
    university: null;
} | {
    closingSoon: null;
} | {
    highestRated: null;
} | {
    skills: null;
} {
    return value == RecommendationMode.bestValue ? {
        bestValue: null
    } : value == RecommendationMode.university ? {
        university: null
    } : value == RecommendationMode.closingSoon ? {
        closingSoon: null
    } : value == RecommendationMode.highestRated ? {
        highestRated: null
    } : value == RecommendationMode.skills ? {
        skills: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Category>): Array<_Category> {
    return value.map((x)=>to_candid_Category_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
